# Generated by Django 5.2 on 2025-05-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createblog',
            name='video',
            field=models.FileField(blank=True, help_text='Formats acceptés : MP4, WebM, Ogg', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='createblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
